services:
  # A Docker web service
  - type: web
    name: drowsiness-detector
    runtime: docker
    plan: free
    region: ohio
    envVars:
      - key: PORT
        value: 8501
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /_stcore/health