name: Deploy to Azure Web App - Drowsiness

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Change as per your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Drowsiness'  # ✅ Replace with your actual Azure App name
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_359025e82038484790cc6828a414e8bf }}
        package: .
